-- Layer separation. raw = as delivered, staging = typed and flagged,
CREATE SCHEMA IF NOT EXISTS raw;
CREATE SCHEMA IF NOT EXISTS staging;
CREATE SCHEMA IF NOT EXISTS mart;
CREATE SCHEMA IF NOT EXISTS meta;

-- One row per pipeline run. Makes "when did this row arrive and from which file"
CREATE TABLE IF NOT EXISTS meta.load_batch (
    batch_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_file    TEXT        NOT NULL,
    started_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at    TIMESTAMPTZ,
    rows_extracted INT,
    rows_staged    INT,
    rows_rejected  INT,
    status         TEXT        NOT NULL DEFAULT 'running'
);

-- Quality check history. Writing results to a table rather than printing them means
CREATE TABLE IF NOT EXISTS meta.dq_result (
    dq_result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id     BIGINT REFERENCES meta.load_batch(batch_id),
    check_name   TEXT        NOT NULL,
    severity     TEXT        NOT NULL,
    observed     NUMERIC,
    expected     NUMERIC,
    passed       BOOLEAN     NOT NULL,
    detail       TEXT,
    checked_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
