-- Landing zone. Every column is TEXT on purpose: coercing on arrival would hide
-- exactly the problems the pipeline exists to find. "N/A" stays "N/A" here.
--
-- Primary key is a hash of the row contents, which is what makes re-running the
-- extract a no-op rather than a duplicate load.
CREATE TABLE IF NOT EXISTS raw.sales_raw (
    _row_hash       TEXT PRIMARY KEY,
    _source_file    TEXT        NOT NULL,
    _ingested_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    _source_line_no INT,

    transaction_id          TEXT,
    invoice_number          TEXT,
    transaction_date        TEXT,
    transaction_time        TEXT,
    transaction_status      TEXT,
    store_id                TEXT,
    store_name              TEXT,
    store_location          TEXT,
    store_type              TEXT,
    store_size_sqm          TEXT,
    district_id             TEXT,
    district_name           TEXT,
    postal_code             TEXT,
    customer_id             TEXT,
    customer_name           TEXT,
    customer_email          TEXT,
    customer_loyalty_status TEXT,
    product_id              TEXT,
    product_name            TEXT,
    product_category        TEXT,
    product_subcategory     TEXT,
    product_brand           TEXT,
    product_department      TEXT,
    supplier_id             TEXT,
    supplier_name           TEXT,
    quantity                TEXT,
    unit_price              TEXT,
    base_price              TEXT,
    discount_rate           TEXT,
    discount_applied        TEXT,
    total_amount            TEXT,
    tax_rate                TEXT,
    tax_amount              TEXT,
    payment_method          TEXT,
    sales_staff_id          TEXT,
    sales_staff_name        TEXT,
    promotion_id            TEXT,
    promotion_name          TEXT
);

-- Quarantine, not deletion. A row lands here only if it cannot be typed at all.
-- The full payload is kept as JSON so a rejected row can be inspected and replayed.
CREATE TABLE IF NOT EXISTS raw.rejects (
    reject_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id       BIGINT REFERENCES meta.load_batch(batch_id),
    _row_hash      TEXT,
    transaction_id TEXT,
    reason_code    TEXT        NOT NULL,
    reason_detail  TEXT,
    payload        JSONB,
    rejected_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
