-- Five dimensions. dim_supplier is the one snowflake arm, hanging off dim_product,
-- because a supplier is a real entity that will grow its own attributes. Geography
-- stays flat inside dim_store: district and postal code are labels, not entities.
--
-- Every dimension carries a -1 Unknown member. That is what lets every foreign key
-- on the fact be NOT NULL despite 23.5% of source rows having no customer, and turns
-- "walk-in" into a queryable segment rather than an absence.

CREATE TABLE IF NOT EXISTS mart.dim_supplier (
    supplier_key  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id   INT  NOT NULL UNIQUE,
    supplier_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS mart.dim_product (
    product_key  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id   INT  NOT NULL UNIQUE,
    product_name TEXT NOT NULL,
    category     TEXT,
    subcategory  TEXT,
    brand        TEXT,
    department   TEXT NOT NULL DEFAULT 'Unassigned',
    base_price   NUMERIC(12,2),
    supplier_key INT  NOT NULL REFERENCES mart.dim_supplier(supplier_key),
    CONSTRAINT ck_product_base_price CHECK (base_price IS NULL OR base_price >= 0)
);

CREATE TABLE IF NOT EXISTS mart.dim_store (
    store_key      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id       INT  NOT NULL UNIQUE,
    store_name     TEXT NOT NULL,
    store_type     TEXT,
    store_location TEXT,
    district_name  TEXT,
    postal_code    TEXT,
    store_size_sqm INT,
    -- Store 6 ships as "Imaginary Store", -500 sqm, district "Unknown", PLZ 00000,
    -- but its 5,154 transactions are ordinary. The master record is fabricated, the
    -- transactions are not, so the facts are kept and the dimension row is marked.
    is_placeholder BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT ck_store_sqm CHECK (store_size_sqm IS NULL OR store_size_sqm > 0)
);

CREATE TABLE IF NOT EXISTS mart.dim_customer (
    customer_key   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    INT  NOT NULL UNIQUE,
    -- To pseudonymise instead, rename this to customer_pseudonym and have the
    -- transform write a salted HMAC of the name. Nothing else in the model changes.
    customer_name  TEXT NOT NULL,
    email_domain   TEXT,
    loyalty_status TEXT NOT NULL DEFAULT 'Unknown',
    -- SCD Type 2 columns, populated with open-ended validity. The loader runs Type 1
    -- because the source shows zero attribute drift; adding versioning later is then
    -- a loader change rather than a schema migration.
    valid_from     DATE    NOT NULL DEFAULT DATE '1900-01-01',
    valid_to       DATE    NOT NULL DEFAULT DATE '9999-12-31',
    is_current     BOOLEAN NOT NULL DEFAULT TRUE
);

-- Generated, never sourced from the CSV. A date dimension built only from observed
-- dates has gaps on exactly the days with no sales, which is where analysis needs it.
CREATE TABLE IF NOT EXISTS mart.dim_date (
    date_key            INT     PRIMARY KEY,
    full_date           DATE    NOT NULL UNIQUE,
    year                INT     NOT NULL,
    quarter             INT     NOT NULL,
    month               INT     NOT NULL,
    month_name          TEXT    NOT NULL,
    day_of_month        INT     NOT NULL,
    day_of_week         INT     NOT NULL,
    day_name            TEXT    NOT NULL,
    iso_week            INT     NOT NULL,
    is_weekend          BOOLEAN NOT NULL,
    is_bavarian_holiday BOOLEAN NOT NULL,
    holiday_name        TEXT
);

-- ---------------------------------------------------------------------------
-- Unknown members, key -1 in every dimension.
-- ---------------------------------------------------------------------------
INSERT INTO mart.dim_supplier (supplier_key, supplier_id, supplier_name)
VALUES (-1, -1, 'Unknown') ON CONFLICT (supplier_key) DO NOTHING;

INSERT INTO mart.dim_product (product_key, product_id, product_name, department, supplier_key)
VALUES (-1, -1, 'Unknown', 'Unassigned', -1) ON CONFLICT (product_key) DO NOTHING;

INSERT INTO mart.dim_store (store_key, store_id, store_name, is_placeholder)
VALUES (-1, -1, 'Unknown', TRUE) ON CONFLICT (store_key) DO NOTHING;

-- Used by the 8,380 rows (23.5%) with no customer_id.
INSERT INTO mart.dim_customer (customer_key, customer_id, customer_name, loyalty_status)
VALUES (-1, -1, 'Walk-in', 'Unknown') ON CONFLICT (customer_key) DO NOTHING;

-- ---------------------------------------------------------------------------
-- dim_date. Generated from a series, with Bavarian public holidays.
-- ---------------------------------------------------------------------------
INSERT INTO mart.dim_date (
    date_key, full_date, year, quarter, month, month_name,
    day_of_month, day_of_week, day_name, iso_week,
    is_weekend, is_bavarian_holiday, holiday_name
)
SELECT
    TO_CHAR(d, 'YYYYMMDD')::INT,
    d::DATE,
    EXTRACT(YEAR    FROM d)::INT,
    EXTRACT(QUARTER FROM d)::INT,
    EXTRACT(MONTH   FROM d)::INT,
    TRIM(TO_CHAR(d, 'Month')),
    EXTRACT(DAY     FROM d)::INT,
    EXTRACT(ISODOW  FROM d)::INT,
    TRIM(TO_CHAR(d, 'Day')),
    EXTRACT(WEEK    FROM d)::INT,
    EXTRACT(ISODOW  FROM d) >= 6,
    h.holiday_name IS NOT NULL,
    h.holiday_name
FROM generate_series(DATE '2024-01-01', DATE '2026-12-31', INTERVAL '1 day') AS d
LEFT JOIN (VALUES
    (DATE '2024-01-01','Neujahr'),(DATE '2024-01-06','Heilige Drei Koenige'),
    (DATE '2024-03-29','Karfreitag'),(DATE '2024-04-01','Ostermontag'),
    (DATE '2024-05-01','Tag der Arbeit'),(DATE '2024-05-09','Christi Himmelfahrt'),
    (DATE '2024-05-20','Pfingstmontag'),(DATE '2024-05-30','Fronleichnam'),
    (DATE '2024-08-15','Mariae Himmelfahrt'),(DATE '2024-10-03','Tag der Deutschen Einheit'),
    (DATE '2024-11-01','Allerheiligen'),(DATE '2024-12-25','1. Weihnachtstag'),
    (DATE '2024-12-26','2. Weihnachtstag'),
    (DATE '2025-01-01','Neujahr'),(DATE '2025-01-06','Heilige Drei Koenige'),
    (DATE '2025-04-18','Karfreitag'),(DATE '2025-04-21','Ostermontag'),
    (DATE '2025-05-01','Tag der Arbeit'),(DATE '2025-05-29','Christi Himmelfahrt'),
    (DATE '2025-06-09','Pfingstmontag'),(DATE '2025-06-19','Fronleichnam'),
    (DATE '2025-08-15','Mariae Himmelfahrt'),(DATE '2025-10-03','Tag der Deutschen Einheit'),
    (DATE '2025-11-01','Allerheiligen'),(DATE '2025-12-25','1. Weihnachtstag'),
    (DATE '2025-12-26','2. Weihnachtstag'),
    (DATE '2026-01-01','Neujahr'),(DATE '2026-01-06','Heilige Drei Koenige'),
    (DATE '2026-04-03','Karfreitag'),(DATE '2026-04-06','Ostermontag'),
    (DATE '2026-05-01','Tag der Arbeit'),(DATE '2026-05-14','Christi Himmelfahrt'),
    (DATE '2026-05-25','Pfingstmontag'),(DATE '2026-06-04','Fronleichnam'),
    (DATE '2026-08-15','Mariae Himmelfahrt'),(DATE '2026-10-03','Tag der Deutschen Einheit'),
    (DATE '2026-11-01','Allerheiligen'),(DATE '2026-12-25','1. Weihnachtstag'),
    (DATE '2026-12-26','2. Weihnachtstag')
) AS h(holiday_date, holiday_name) ON h.holiday_date = d::DATE
ON CONFLICT (date_key) DO NOTHING;

INSERT INTO mart.dim_date (date_key, full_date, year, quarter, month, month_name,
    day_of_month, day_of_week, day_name, iso_week, is_weekend, is_bavarian_holiday)
VALUES (-1, DATE '1900-01-01', 1900, 1, 1, 'Unknown', 1, 1, 'Unknown', 1, FALSE, FALSE)
ON CONFLICT (date_key) DO NOTHING;
