-- Grain: one row = one product line on one transaction = one row in the CSV.
--
-- NOT one row per invoice. Of the 5,416 invoice numbers appearing on more than one
-- row, 5,397 carry conflicting transaction dates and 4,509 conflicting store ids.
-- invoice_number is a colliding random string, so it is stored as a DEGENERATE
-- DIMENSION: an attribute on the fact with no dimension table and no foreign key,
-- because it identifies nothing.
--
-- transaction_status, payment_method, sales_staff_name and promotion_name are also
-- degenerate. Each is a low-cardinality label with no attributes of its own, so a
-- dimension table would add a join and carry nothing.
CREATE TABLE IF NOT EXISTS mart.fact_sales (
    sale_key       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- TEXT, not UUID: 689 unique source ids are not UUID-shaped. Also the conflict
    -- target that makes the fact load an upsert rather than a duplicate.
    transaction_id TEXT NOT NULL UNIQUE,
    invoice_number TEXT,

    date_key       INT NOT NULL REFERENCES mart.dim_date(date_key),
    store_key      INT NOT NULL REFERENCES mart.dim_store(store_key),
    product_key    INT NOT NULL REFERENCES mart.dim_product(product_key),
    customer_key   INT NOT NULL REFERENCES mart.dim_customer(customer_key),

    transaction_time   TIME,
    transaction_status TEXT NOT NULL,
    payment_method     TEXT,
    sales_staff_name   TEXT,
    promotion_name     TEXT,

    quantity      INT,
    unit_price    NUMERIC(12,2),
    base_price    NUMERIC(12,2),
    discount_rate NUMERIC(6,4),
    tax_rate      NUMERIC(5,4),
    tax_amount    NUMERIC(14,2),

    -- Canonical net revenue, computed as quantity * unit_price rather than taken
    -- from the source. unit_price = base_price * (1 - discount_rate) holds for 100%
    -- of rows while total_amount = quantity * unit_price holds for only 97.1%, so
    -- the price side is trustworthy and the delivered total is not.
    total_amount     NUMERIC(14,2),
    -- What the source actually said. Kept because when 2.9% of rows disagree with
    -- their own arithmetic you do not get to silently pick one and discard the other.
    total_amount_raw NUMERIC(14,2),

    -- Quality bitmask. Nothing is deleted to make the numbers look clean: suspect
    -- rows load with a bit set and the views decide what to exclude.
    dq_flags  INT    NOT NULL DEFAULT 0,
    batch_id  BIGINT REFERENCES meta.load_batch(batch_id),
    loaded_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON COLUMN mart.fact_sales.dq_flags IS
'Bitmask. 1=total mismatch, 2=quantity outlier, 4=discount out of range, 8=negative qty on completed, 16=placeholder store, 32=repaired from N/A, 64=missing customer, 128=discount flag conflict, 256=unparsed date, 512=non-uuid transaction id, 1024=unparseable email domain';
